# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 22:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 22, 32, 30, 867312, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
